# Generated by Django 3.1.2 on 2020-10-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201006_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
