# Generated by Django 3.1.2 on 2020-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_bio_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bio',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, to='base.Skill'),
        ),
        migrations.AddField(
            model_name='bio',
            name='softSkill',
            field=models.ManyToManyField(blank=True, null=True, to='base.SoftSkill'),
        ),
    ]
